runtime: python312

instance_class: F1

automatic_scaling:
  min_instances: 1
  max_instances: 2

includes:
  - env.yaml

handlers:
  - url: /.*
    script: auto
    secure: always

entrypoint: gunicorn -b :$PORT main:app
